import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import Sidebar from "@/components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={""}>
        <div className="ml-[240px] mt-[60px]">
          <div className="fixed left-0 top-0 z-[1000] w-full">
            <Header />
            <Sidebar />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
